version: 2.1
orbs:
  node: circleci/node@2.0.1
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Configure dependencies
          command: |
            git config user.email "markanthonylumbao@gmail.com"
            git config user.name "Mark Anthony Lumbao"
      - run: npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "bd:ef:73:66:56:b4:3b:bc:32:b5:b5:51:13:9d:48:3b"
  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
    build-test-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
        - deploy-staging:
            requires:
              - build
            filters:
              branches:
                only: dev