version: 2.1
orbs:
  node: circleci/node@2.0.1
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Configure dependencies
          command: |
            git config user.email "markanthonylumbao@gmail.com"
            git config user.name "Mark Anthony Lumbao"
      - add_ssh_keys:
          fingerprints:
            - "67:0c:52:9d:ff:4b:36:46:09:8f:b4:be:4a:44:7a:b8"
      - run: npm run deploy
  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
    build-test-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
        - deploy-staging:
            requires:
              - build
            filters:
              branches:
                only: dev