version: 2.1
orbs:
  node: circleci/node@2.0.1
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
    build-test-deploy:
      jobs:
        - build-and-test
        - deploy:  
            requires:
              - build-and-test
            filters:
              branches:
                only: master